apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # এটি ইনভার্টেড কমার ভেতরে খালি রাখা খুব জরুরি
  resources:
    requests:
      storage: 5Gi
